### PR TITLE
Make Install Scripts Repeatable, Add Uninstall script, and Update README with Instructions

### PR DESCRIPTION
**Pull request by Matt-Retrogamer**
These changes will improve the usability and maintainability of the installation process, allowing users to easily update their setup without manual intervention.

Description:
- Modified `Setup_MrFusion.sh` and `Install_MrFusion.sh` to ensure all operations are repeatable, making the scripts suitable for both initial installations and updates.
- Updated `README.md` to include a new section titled "Updating to the Latest Version" with detailed steps for users to update their existing setup (+ a few minor typo fixes).
- Added `Uninstall_MrFusion.sh` uninstallation script + instructions to `README.md`.
- Updated file permissions for `Install_MrFusion.sh` and `Setup_MrFusion.sh` to be executable.

Please review the changes and let me know if any adjustments are needed. Thank you!

### CODE REVIEW

**Comment by Matt-Retrogamer** [comment]
- Added "Uninstall_MrFusion.sh" uninstallation script + instructions to README.md.
- Updated file permissions for Install_MrFusion.sh and Setup_MrFusion.sh to be executable.

**Comment by MrLightgun** [comment]
This is awesome, thank you @Matt-Retrogamer

**Comment by Matt-Retrogamer** [comment]
> This is awesome, thank you @Matt-Retrogamer

My pleasure, thanks for the great integration!
There's still room for improvement, I think the next step would be to package the project to be compatible with update_all. I would wait to see if some elements like the overlay are integrated in the base MiSTer framework before doing that though.

**Comment by Matt-Retrogamer** [comment]
BTW @MrLightgun , I think you have reverted my changes after merging the pull request, now the scripts are back to the state that they add before I forked...

**Pull request merged**
